### ISSUE TITLE
Model is inverted

### ISSUE THREAD

**Issue by jason11040** [Raitou/P3M-Importer-Exporter#1]
Been working on a frm importer because it hasn't been done yet and we come across a problem or so we think. Comparing the frm matrix's to p3m matrixs it seems the bones are not right. I wish you had a discord of some sort but i can show you some pics.

Blender p3m code import
https://i.imgur.com/cTgpTsK.png

frm with p3m in studio code
https://i.imgur.com/FwrTX0A.png

You can see the weapon being in the wrong side of the p3m model.

**Comment by Raitou** [comment]
Ah, I never worked with FRM so I wouldn't know. It is been a while since I worked on it so I might not remember. Anyways here is my discord if u needed ```Anya Forger#7825```
